export type Country = {
  code: string;
  name: string;
  numericId: string;
};

/** UN member states + common travel destinations (~195) */
export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", numericId: "004" },
  { code: "AL", name: "Albania", numericId: "008" },
  { code: "DZ", name: "Algeria", numericId: "012" },
  { code: "AD", name: "Andorra", numericId: "020" },
  { code: "AO", name: "Angola", numericId: "024" },
  { code: "AG", name: "Antigua and Barbuda", numericId: "028" },
  { code: "AR", name: "Argentina", numericId: "032" },
  { code: "AM", name: "Armenia", numericId: "051" },
  { code: "AU", name: "Australia", numericId: "036" },
  { code: "AT", name: "Austria", numericId: "040" },
  { code: "AZ", name: "Azerbaijan", numericId: "031" },
  { code: "BS", name: "Bahamas", numericId: "044" },
  { code: "BH", name: "Bahrain", numericId: "048" },
  { code: "BD", name: "Bangladesh", numericId: "050" },
  { code: "BB", name: "Barbados", numericId: "052" },
  { code: "BY", name: "Belarus", numericId: "112" },
  { code: "BE", name: "Belgium", numericId: "056" },
  { code: "BZ", name: "Belize", numericId: "084" },
  { code: "BJ", name: "Benin", numericId: "204" },
  { code: "BT", name: "Bhutan", numericId: "064" },
  { code: "BO", name: "Bolivia", numericId: "068" },
  { code: "BA", name: "Bosnia and Herzegovina", numericId: "070" },
  { code: "BW", name: "Botswana", numericId: "072" },
  { code: "BR", name: "Brazil", numericId: "076" },
  { code: "BN", name: "Brunei", numericId: "096" },
  { code: "BG", name: "Bulgaria", numericId: "100" },
  { code: "BF", name: "Burkina Faso", numericId: "854" },
  { code: "BI", name: "Burundi", numericId: "108" },
  { code: "CV", name: "Cabo Verde", numericId: "132" },
  { code: "KH", name: "Cambodia", numericId: "116" },
  { code: "CM", name: "Cameroon", numericId: "120" },
  { code: "CA", name: "Canada", numericId: "124" },
  { code: "CF", name: "Central African Republic", numericId: "140" },
  { code: "TD", name: "Chad", numericId: "148" },
  { code: "CL", name: "Chile", numericId: "152" },
  { code: "CN", name: "China", numericId: "156" },
  { code: "CO", name: "Colombia", numericId: "170" },
  { code: "KM", name: "Comoros", numericId: "174" },
  { code: "CG", name: "Congo", numericId: "178" },
  { code: "CD", name: "DR Congo", numericId: "180" },
  { code: "CR", name: "Costa Rica", numericId: "188" },
  { code: "CI", name: "Côte d'Ivoire", numericId: "384" },
  { code: "HR", name: "Croatia", numericId: "191" },
  { code: "CU", name: "Cuba", numericId: "192" },
  { code: "CY", name: "Cyprus", numericId: "196" },
  { code: "CZ", name: "Czechia", numericId: "203" },
  { code: "DK", name: "Denmark", numericId: "208" },
  { code: "DJ", name: "Djibouti", numericId: "262" },
  { code: "DM", name: "Dominica", numericId: "212" },
  { code: "DO", name: "Dominican Republic", numericId: "214" },
  { code: "EC", name: "Ecuador", numericId: "218" },
  { code: "EG", name: "Egypt", numericId: "818" },
  { code: "SV", name: "El Salvador", numericId: "222" },
  { code: "GQ", name: "Equatorial Guinea", numericId: "226" },
  { code: "ER", name: "Eritrea", numericId: "232" },
  { code: "EE", name: "Estonia", numericId: "233" },
  { code: "SZ", name: "Eswatini", numericId: "748" },
  { code: "ET", name: "Ethiopia", numericId: "231" },
  { code: "FJ", name: "Fiji", numericId: "242" },
  { code: "FI", name: "Finland", numericId: "246" },
  { code: "FR", name: "France", numericId: "250" },
  { code: "GA", name: "Gabon", numericId: "266" },
  { code: "GM", name: "Gambia", numericId: "270" },
  { code: "GE", name: "Georgia", numericId: "268" },
  { code: "DE", name: "Germany", numericId: "276" },
  { code: "GH", name: "Ghana", numericId: "288" },
  { code: "GR", name: "Greece", numericId: "300" },
  { code: "GD", name: "Grenada", numericId: "308" },
  { code: "GT", name: "Guatemala", numericId: "320" },
  { code: "GN", name: "Guinea", numericId: "324" },
  { code: "GW", name: "Guinea-Bissau", numericId: "624" },
  { code: "GY", name: "Guyana", numericId: "328" },
  { code: "HT", name: "Haiti", numericId: "332" },
  { code: "HN", name: "Honduras", numericId: "340" },
  { code: "HU", name: "Hungary", numericId: "348" },
  { code: "IS", name: "Iceland", numericId: "352" },
  { code: "IN", name: "India", numericId: "356" },
  { code: "ID", name: "Indonesia", numericId: "360" },
  { code: "IR", name: "Iran", numericId: "364" },
  { code: "IQ", name: "Iraq", numericId: "368" },
  { code: "IE", name: "Ireland", numericId: "372" },
  { code: "IL", name: "Israel", numericId: "376" },
  { code: "IT", name: "Italy", numericId: "380" },
  { code: "JM", name: "Jamaica", numericId: "388" },
  { code: "JP", name: "Japan", numericId: "392" },
  { code: "JO", name: "Jordan", numericId: "400" },
  { code: "KZ", name: "Kazakhstan", numericId: "398" },
  { code: "KE", name: "Kenya", numericId: "404" },
  { code: "KI", name: "Kiribati", numericId: "296" },
  { code: "KP", name: "North Korea", numericId: "408" },
  { code: "KR", name: "South Korea", numericId: "410" },
  { code: "KW", name: "Kuwait", numericId: "414" },
  { code: "KG", name: "Kyrgyzstan", numericId: "417" },
  { code: "LA", name: "Laos", numericId: "418" },
  { code: "LV", name: "Latvia", numericId: "428" },
  { code: "LB", name: "Lebanon", numericId: "422" },
  { code: "LS", name: "Lesotho", numericId: "426" },
  { code: "LR", name: "Liberia", numericId: "430" },
  { code: "LY", name: "Libya", numericId: "434" },
  { code: "LI", name: "Liechtenstein", numericId: "438" },
  { code: "LT", name: "Lithuania", numericId: "440" },
  { code: "LU", name: "Luxembourg", numericId: "442" },
  { code: "MG", name: "Madagascar", numericId: "450" },
  { code: "MW", name: "Malawi", numericId: "454" },
  { code: "MY", name: "Malaysia", numericId: "458" },
  { code: "MV", name: "Maldives", numericId: "462" },
  { code: "ML", name: "Mali", numericId: "466" },
  { code: "MT", name: "Malta", numericId: "470" },
  { code: "MH", name: "Marshall Islands", numericId: "584" },
  { code: "MR", name: "Mauritania", numericId: "478" },
  { code: "MU", name: "Mauritius", numericId: "480" },
  { code: "MX", name: "Mexico", numericId: "484" },
  { code: "FM", name: "Micronesia", numericId: "583" },
  { code: "MD", name: "Moldova", numericId: "498" },
  { code: "MC", name: "Monaco", numericId: "492" },
  { code: "MN", name: "Mongolia", numericId: "496" },
  { code: "ME", name: "Montenegro", numericId: "499" },
  { code: "MA", name: "Morocco", numericId: "504" },
  { code: "MZ", name: "Mozambique", numericId: "508" },
  { code: "MM", name: "Myanmar", numericId: "104" },
  { code: "NA", name: "Namibia", numericId: "516" },
  { code: "NR", name: "Nauru", numericId: "520" },
  { code: "NP", name: "Nepal", numericId: "524" },
  { code: "NL", name: "Netherlands", numericId: "528" },
  { code: "NZ", name: "New Zealand", numericId: "554" },
  { code: "NI", name: "Nicaragua", numericId: "558" },
  { code: "NE", name: "Niger", numericId: "562" },
  { code: "NG", name: "Nigeria", numericId: "566" },
  { code: "MK", name: "North Macedonia", numericId: "807" },
  { code: "NO", name: "Norway", numericId: "578" },
  { code: "OM", name: "Oman", numericId: "512" },
  { code: "PK", name: "Pakistan", numericId: "586" },
  { code: "PW", name: "Palau", numericId: "585" },
  { code: "PS", name: "Palestine", numericId: "275" },
  { code: "PA", name: "Panama", numericId: "591" },
  { code: "PG", name: "Papua New Guinea", numericId: "598" },
  { code: "PY", name: "Paraguay", numericId: "600" },
  { code: "PE", name: "Peru", numericId: "604" },
  { code: "PH", name: "Philippines", numericId: "608" },
  { code: "PL", name: "Poland", numericId: "616" },
  { code: "PT", name: "Portugal", numericId: "620" },
  { code: "QA", name: "Qatar", numericId: "634" },
  { code: "RO", name: "Romania", numericId: "642" },
  { code: "RU", name: "Russia", numericId: "643" },
  { code: "RW", name: "Rwanda", numericId: "646" },
  { code: "KN", name: "Saint Kitts and Nevis", numericId: "659" },
  { code: "LC", name: "Saint Lucia", numericId: "662" },
  { code: "VC", name: "Saint Vincent and the Grenadines", numericId: "670" },
  { code: "WS", name: "Samoa", numericId: "882" },
  { code: "SM", name: "San Marino", numericId: "674" },
  { code: "ST", name: "São Tomé and Príncipe", numericId: "678" },
  { code: "SA", name: "Saudi Arabia", numericId: "682" },
  { code: "SN", name: "Senegal", numericId: "686" },
  { code: "RS", name: "Serbia", numericId: "688" },
  { code: "SC", name: "Seychelles", numericId: "690" },
  { code: "SL", name: "Sierra Leone", numericId: "694" },
  { code: "SG", name: "Singapore", numericId: "702" },
  { code: "SK", name: "Slovakia", numericId: "703" },
  { code: "SI", name: "Slovenia", numericId: "705" },
  { code: "SB", name: "Solomon Islands", numericId: "090" },
  { code: "SO", name: "Somalia", numericId: "706" },
  { code: "ZA", name: "South Africa", numericId: "710" },
  { code: "SS", name: "South Sudan", numericId: "728" },
  { code: "ES", name: "Spain", numericId: "724" },
  { code: "LK", name: "Sri Lanka", numericId: "144" },
  { code: "SD", name: "Sudan", numericId: "729" },
  { code: "SR", name: "Suriname", numericId: "740" },
  { code: "SE", name: "Sweden", numericId: "752" },
  { code: "CH", name: "Switzerland", numericId: "756" },
  { code: "SY", name: "Syria", numericId: "760" },
  { code: "TW", name: "Taiwan", numericId: "158" },
  { code: "TJ", name: "Tajikistan", numericId: "762" },
  { code: "TZ", name: "Tanzania", numericId: "834" },
  { code: "TH", name: "Thailand", numericId: "764" },
  { code: "TL", name: "Timor-Leste", numericId: "626" },
  { code: "TG", name: "Togo", numericId: "768" },
  { code: "TO", name: "Tonga", numericId: "776" },
  { code: "TT", name: "Trinidad and Tobago", numericId: "780" },
  { code: "TN", name: "Tunisia", numericId: "788" },
  { code: "TR", name: "Turkey", numericId: "792" },
  { code: "TM", name: "Turkmenistan", numericId: "795" },
  { code: "TV", name: "Tuvalu", numericId: "798" },
  { code: "UG", name: "Uganda", numericId: "800" },
  { code: "UA", name: "Ukraine", numericId: "804" },
  { code: "AE", name: "United Arab Emirates", numericId: "784" },
  { code: "GB", name: "United Kingdom", numericId: "826" },
  { code: "US", name: "United States", numericId: "840" },
  { code: "UY", name: "Uruguay", numericId: "858" },
  { code: "UZ", name: "Uzbekistan", numericId: "860" },
  { code: "VU", name: "Vanuatu", numericId: "548" },
  { code: "VA", name: "Vatican City", numericId: "336" },
  { code: "VE", name: "Venezuela", numericId: "862" },
  { code: "VN", name: "Vietnam", numericId: "704" },
  { code: "YE", name: "Yemen", numericId: "887" },
  { code: "ZM", name: "Zambia", numericId: "894" },
  { code: "ZW", name: "Zimbabwe", numericId: "716" },
];

export const TOTAL_COUNTRIES = COUNTRIES.length;

export const countryByCode = new Map(COUNTRIES.map((c) => [c.code, c]));
export const countryByNumericId = new Map(
  COUNTRIES.map((c) => [c.numericId, c]),
);
export const countryByName = new Map(COUNTRIES.map((c) => [c.name, c]));

export function getCountryName(code: string): string {
  return countryByCode.get(code)?.name ?? code;
}

export function calcStats(visitedCodes: string[]) {
  const visited = visitedCodes.length;
  const percent =
    TOTAL_COUNTRIES > 0
      ? Math.round((visited / TOTAL_COUNTRIES) * 1000) / 10
      : 0;
  return { visited, total: TOTAL_COUNTRIES, percent };
}
