/**
 * Generates src/data/cities.json — capitals + major cities per country.
 * Run: node scripts/generate-cities.mjs
 */
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Capital + optional major cities (English / local names) */
const CITIES = {
  AF: ["Kabul", "Kandahar", "Herat"],
  AL: ["Tirana", "Durrës", "Vlorë"],
  DZ: ["Algiers", "Oran", "Constantine"],
  AD: ["Andorra la Vella"],
  AO: ["Luanda", "Huambo"],
  AG: ["Saint John's"],
  AR: ["Buenos Aires", "Córdoba", "Mendoza", "Bariloche", "Ushuaia"],
  AM: ["Yerevan", "Gyumri"],
  AU: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra"],
  AT: ["Vienna", "Salzburg", "Innsbruck", "Graz"],
  AZ: ["Baku", "Ganja"],
  BS: ["Nassau"],
  BH: ["Manama"],
  BD: ["Dhaka", "Chittagong"],
  BB: ["Bridgetown"],
  BY: ["Minsk", "Brest", "Gomel"],
  BE: ["Brussels", "Bruges", "Antwerp", "Ghent"],
  BZ: ["Belize City"],
  BJ: ["Cotonou", "Porto-Novo"],
  BT: ["Thimphu", "Paro"],
  BO: ["La Paz", "Sucre", "Santa Cruz"],
  BA: ["Sarajevo", "Mostar"],
  BW: ["Gaborone"],
  BR: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Florianópolis"],
  BN: ["Bandar Seri Begawan"],
  BG: ["Sofia", "Plovmotion", "Varna", "Plovmotion"],
  BF: ["Ouagadougou"],
  BI: ["Bujumbura"],
  CV: ["Praia"],
  KH: ["Phnom Penh", "Siem Reap"],
  CM: ["Yaoundé", "Douala"],
  CA: ["Toronto", "Vancouver", "Montreal", "Ottawa", "Calgary", "Quebec City"],
  CF: ["Bangui"],
  TD: ["N'Djamena"],
  CL: ["Santiago", "Valparaíso", "Puerto Varas"],
  CN: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Xi'an"],
  CO: ["Bogotá", "Medellín", "Cartagena", "Cali"],
  KM: ["Moroni"],
  CG: ["Brazzaville"],
  CD: ["Kinshasa", "Lubumbashi"],
  CR: ["San José"],
  CI: ["Abidjan", "Yamoussoukro"],
  HR: ["Zagreb", "Dubrovnik", "Split", "Rijeka"],
  CU: ["Havana", "Varadero"],
  CY: ["Nicosia", "Limassol", "Paphos"],
  CZ: ["Prague", "Brno", "Český Krumlov", "Karlovy Vary"],
  DK: ["Copenhagen", "Aarhus", "Odense"],
  DJ: ["Djibouti"],
  DM: ["Roseau"],
  DO: ["Santo Domingo", "Punta Cana"],
  EC: ["Quito", "Guayaquil", "Galápagos"],
  EG: ["Cairo", "Alexandria", "Luxor", "Aswan", "Hurghada", "Sharm El Sheikh"],
  SV: ["San Salvador"],
  GQ: ["Malabo"],
  ER: ["Asmara"],
  EE: ["Tallinn", "Tartu"],
  SZ: ["Mbabane"],
  ET: ["Addis Ababa"],
  FJ: ["Suva", "Nadi"],
  FI: ["Helsinki", "Tampere", "Rovaniemi", "Turku"],
  FR: ["Paris", "Lyon", "Marseille", "Nice", "Bordeaux", "Strasbourg"],
  GA: ["Libreville"],
  GM: ["Banjul"],
  GE: ["Tbilisi", "Batumi", "Kutaisi"],
  DE: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Dresden"],
  GH: ["Accra", "Kumasi"],
  GR: ["Athens", "Thessaloniki", "Santorini", "Mykonos", "Crete"],
  GD: ["St. George's"],
  GT: ["Guatemala City", "Antigua"],
  GN: ["Conakry"],
  GW: ["Bissau"],
  GY: ["Georgetown"],
  HT: ["Port-au-Prince"],
  HN: ["Tegucigalpa", "Roatán"],
  HU: ["Budapest", "Debrecen", "Szeged"],
  IS: ["Reykjavik", "Akureyri"],
  IN: ["Delhi", "Mumbai", "Bangalore", "Kolkata", "Chennai", "Jaipur", "Goa"],
  ID: ["Jakarta", "Bali", "Surabaya", "Yogyakarta", "Bandung"],
  IR: ["Tehran", "Isfahan", "Shiraz"],
  IQ: ["Baghdad", "Erbil"],
  IE: ["Dublin", "Cork", "Galway"],
  IL: ["Tel Aviv", "Jerusalem", "Haifa", "Eilat"],
  IT: ["Rome", "Milan", "Venice", "Florence", "Naples", "Turin", "Bologna"],
  JM: ["Kingston", "Montego Bay"],
  JP: ["Tokyo", "Osaka", "Kyoto", "Hiroshima", "Sapporo", "Fukuoka"],
  JO: ["Amman", "Petra", "Aqaba"],
  KZ: ["Almaty", "Astana", "Shymkent"],
  KE: ["Nairobi", "Mombasa"],
  KI: ["Tarawa"],
  KP: ["Pyongyang"],
  KR: ["Seoul", "Busan", "Jeju", "Incheon"],
  KW: ["Kuwait City"],
  KG: ["Bishkek", "Osh"],
  LA: ["Vientiane", "Luang Prabang"],
  LV: ["Riga", "Jūrmala"],
  LB: ["Beirut"],
  LS: ["Maseru"],
  LR: ["Monrovia"],
  LY: ["Tripoli", "Benghazi"],
  LI: ["Vaduz"],
  LT: ["Vilnius", "Kaunas"],
  LU: ["Luxembourg City"],
  MG: ["Antananarivo"],
  MW: ["Lilongwe"],
  MY: ["Kuala Lumpur", "Penang", "Langkawi", "Malacca"],
  MV: ["Malé"],
  ML: ["Bamako"],
  MT: ["Valletta"],
  MH: ["Majuro"],
  MR: ["Nouakchott"],
  MU: ["Port Louis"],
  MX: ["Mexico City", "Cancún", "Guadalajara", "Tulum", "Oaxaca", "Playa del Carmen"],
  FM: ["Palikir"],
  MD: ["Chișinău"],
  MC: ["Monaco"],
  MN: ["Ulaanbaatar"],
  ME: ["Podgorica", "Kotor", "Budva"],
  MA: ["Marrakech", "Casablanca", "Fez", "Rabat", "Tangier"],
  MZ: ["Maputo"],
  MM: ["Yangon", "Mandalay", "Bagan"],
  NA: ["Windhoek"],
  NR: ["Yaren"],
  NP: ["Kathmandu", "Pokhara"],
  NL: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"],
  NZ: ["Auckland", "Wellington", "Queenstown", "Christchurch"],
  NI: ["Managua"],
  NE: ["Niamey"],
  NG: ["Lagos", "Abuja"],
  MK: ["Skopje", "Ohrid"],
  NO: ["Oslo", "Bergen", "Tromsø", "Stavanger"],
  OM: ["Muscat", "Salalah"],
  PK: ["Karachi", "Lahore", "Islamabad"],
  PW: ["Ngerulmud"],
  PA: ["Panama City", "Bocas del Toro"],
  PG: ["Port Moresby"],
  PY: ["Asunción"],
  PE: ["Lima", "Cusco", "Arequipa"],
  PH: ["Manila", "Cebu", "Boracay", "Palawan"],
  PL: ["Warsaw", "Kraków", "Gdańsk", "Wrocław", "Poznań"],
  PT: ["Lisbon", "Porto", "Faro", "Madeira"],
  QA: ["Doha"],
  RO: ["Bucharest", "Brașov", "Cluj-Napoca", "Sibiu"],
  RU: ["Москва", "Санкт-Петербург", "Казань", "Сочи", "Новосибирск", "Екатеринбург", "Владивосток", "Калининград", "Самара", "Краснодар"],
  RW: ["Kigali"],
  KN: ["Basseterre"],
  LC: ["Castries"],
  VC: ["Kingstown"],
  WS: ["Apia"],
  SM: ["San Marino"],
  ST: ["São Tomé"],
  SA: ["Riyadh", "Jeddah", "Mecca", "Medina"],
  SN: ["Dakar"],
  RS: ["Belgrade", "Novi Sad"],
  SC: ["Victoria"],
  SL: ["Freetown"],
  SG: ["Singapore"],
  SK: ["Bratislava", "Košice"],
  SI: ["Ljubljana", "Bled"],
  SB: ["Honiara"],
  SO: ["Mogadishu"],
  ZA: ["Cape Town", "Johannesburg", "Durban", "Pretoria"],
  SS: ["Juba"],
  ES: ["Madrid", "Barcelona", "Seville", "Valencia", "Granada", "Bilbao", "Málaga"],
  LK: ["Colombo", "Kandy", "Galle"],
  SD: ["Khartoum"],
  SR: ["Paramaribo"],
  SE: ["Stockholm", "Gothenburg", "Malmö"],
  CH: ["Zurich", "Geneva", "Bern", "Lucerne", "Basel"],
  SY: ["Damascus", "Aleppo"],
  TW: ["Taipei", "Kaohsiung", "Taichung"],
  TJ: ["Dushanbe"],
  TZ: ["Dar es Salaam", "Zanzibar City", "Arusha"],
  TH: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Krabi"],
  TL: ["Dili"],
  TG: ["Lomé"],
  TO: ["Nuku'alofa"],
  TT: ["Port of Spain"],
  TN: ["Tunis", "Sfax"],
  TR: ["Istanbul", "Ankara", "Antalya", "Izmir", "Cappadocia", "Bodrum"],
  TM: ["Ashgabat"],
  TV: ["Funafuti"],
  UG: ["Kampala", "Entebbe"],
  UA: ["Київ", "Львів", "Одеса", "Харків", "Дніпро"],
  AE: ["Dubai", "Abu Dhabi", "Sharjah"],
  GB: ["London", "Edinburgh", "Manchester", "Liverpool", "Bath", "Oxford"],
  US: ["New York", "Los Angeles", "Chicago", "San Francisco", "Miami", "Las Vegas", "Washington", "Boston", "Seattle", "Honolulu"],
  UY: ["Montevideo", "Punta del Este"],
  UZ: ["Tashkent", "Samarkand", "Bukhara"],
  VU: ["Port Vila"],
  VA: ["Vatican City"],
  VE: ["Caracas", "Margarita Island"],
  VN: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hội An", "Nha Trang"],
  YE: ["Sana'a", "Aden"],
  ZM: ["Lusaka", "Livingstone"],
  ZW: ["Harare", "Victoria Falls"],
};

// Fix typo
CITIES.BG = ["Sofia", "Plovdiv", "Varna"];

import { readFileSync } from "fs";
const countriesPath = join(__dirname, "../src/lib/countries.ts");
const codes = [...readFileSync(countriesPath, "utf8").matchAll(/code: "([A-Z]{2})"/g)].map(
  (m) => m[1],
);

const out = {};
for (const code of codes) {
  out[code] = CITIES[code] ?? [`${code} City`];
}

const outPath = join(__dirname, "../src/data/cities.json");
writeFileSync(outPath, JSON.stringify(out));
console.log(`Wrote ${outPath} (${codes.length} countries)`);
